#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: Visual Studio 2019

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - cmd: powershell -NoProfile -ExecutionPolicy unrestricted -Command .\appveyor.ps1
  - ps: .\build.ps1 -Target AppVeyor

# Tests
test: off

#---------------------------------#
#        Branches to build        #
#---------------------------------#
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
- Source\packages -> Source\**\packages.config
- tools -> setup.cake